version: '3.8'

services:
  jobmanager:
    image: flink:1.19
    hostname: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        metrics.enabled: true
    ports:
      - "8081:8081"
    command: jobmanager
    networks:
      - flink-network

  taskmanager:
    image: flink:1.19
    hostname: taskmanager

    environment:
      - |
        FLINK_PROPERTIES=
        metrics.enabled: true
        metrics.reporter.influxdb.factory.class: org.apache.flink.metrics.influxdb.InfluxdbReporterFactory
        metrics.reporter.influxdb.host: influxdb
        metrics.reporter.influxdb.protocol: http
        metrics.reporter.influxdb.port: 8086
        metrics.reporter.influxdb.db: flink_metrics
        metrics.reporter.influxdb.interval: 10 SECONDS
        jobmanager.rpc.address: jobmanager
    command: taskmanager
    depends_on:
      - jobmanager
    networks:
      - flink-network

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=flink_metrics
    networks:
      - flink-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - flink-network

volumes:
  grafana-storage:
    driver: local

networks:
  flink-network:
    driver: bridge